import type { Metadata } from "next";
import { Comforter } from "next/font/google";
import "./globals.css";

const inter = Comforter({
  subsets: ["latin"],
  display: 'swap',
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} antialiased`}>

        {children}
      </body>
    </html>
  );
}
